// Automatically generated by MockGen. DO NOT EDIT!
// Source: kego.io/editor/shared/messages (interfaces: Message)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	messages "kego.io/editor/shared/messages"
)

// Mock of Message interface
type MockMessage struct {
	ctrl     *gomock.Controller
	recorder *_MockMessageRecorder
}

// Recorder for MockMessage (not exported)
type _MockMessageRecorder struct {
	mock *MockMessage
}

func NewMockMessage(ctrl *gomock.Controller) *MockMessage {
	mock := &MockMessage{ctrl: ctrl}
	mock.recorder = &_MockMessageRecorder{mock}
	return mock
}

func (_m *MockMessage) EXPECT() *_MockMessageRecorder {
	return _m.recorder
}

func (_m *MockMessage) Message() *messages.Message_base {
	ret := _m.ctrl.Call(_m, "Message")
	ret0, _ := ret[0].(*messages.Message_base)
	return ret0
}

func (_mr *_MockMessageRecorder) Message() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Message")
}
