language: go
go:
    - 1.7
go_import_path: kego.io/
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
addons:
  apt:
    packages:
      - nodejs
install:
  - go get -u github.com/gopherjs/gopherjs
  - go get -u github.com/dave/kerr/kcov
  - go get -t -v ./...
script:
  - kcov -r kego.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
