language: go
go:
    - 1.8
go_import_path: kego.io/
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
addons:
  apt:
    packages:
      - nodejs
install:
  - go get -u github.com/gopherjs/gopherjs
  - go get -u github.com/dave/courtney
  - go get -t -v ./...
script:
  - courtney kego.io/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
