// Automatically generated by MockGen. DO NOT EDIT!
// Source: kego.io/flux (interfaces: DispatcherInterface,NotifierInterface)

package mock_flux

import (
	gomock "github.com/golang/mock/gomock"
	flux "kego.io/flux"
)

// Mock of DispatcherInterface interface
type MockDispatcherInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockDispatcherInterfaceRecorder
}

// Recorder for MockDispatcherInterface (not exported)
type _MockDispatcherInterfaceRecorder struct {
	mock *MockDispatcherInterface
}

func NewMockDispatcherInterface(ctrl *gomock.Controller) *MockDispatcherInterface {
	mock := &MockDispatcherInterface{ctrl: ctrl}
	mock.recorder = &_MockDispatcherInterfaceRecorder{mock}
	return mock
}

func (_m *MockDispatcherInterface) EXPECT() *_MockDispatcherInterfaceRecorder {
	return _m.recorder
}

func (_m *MockDispatcherInterface) Dispatch(_param0 flux.ActionInterface) chan struct{} {
	ret := _m.ctrl.Call(_m, "Dispatch", _param0)
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

func (_mr *_MockDispatcherInterfaceRecorder) Dispatch(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Dispatch", arg0)
}

// Mock of NotifierInterface interface
type MockNotifierInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockNotifierInterfaceRecorder
}

// Recorder for MockNotifierInterface (not exported)
type _MockNotifierInterfaceRecorder struct {
	mock *MockNotifierInterface
}

func NewMockNotifierInterface(ctrl *gomock.Controller) *MockNotifierInterface {
	mock := &MockNotifierInterface{ctrl: ctrl}
	mock.recorder = &_MockNotifierInterfaceRecorder{mock}
	return mock
}

func (_m *MockNotifierInterface) EXPECT() *_MockNotifierInterfaceRecorder {
	return _m.recorder
}

func (_m *MockNotifierInterface) Notify(_param0 interface{}, _param1 flux.Notif) chan struct{} {
	ret := _m.ctrl.Call(_m, "Notify", _param0, _param1)
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

func (_mr *_MockNotifierInterfaceRecorder) Notify(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Notify", arg0, arg1)
}

func (_m *MockNotifierInterface) NotifyWithData(_param0 interface{}, _param1 flux.Notif, _param2 interface{}) chan struct{} {
	ret := _m.ctrl.Call(_m, "NotifyWithData", _param0, _param1, _param2)
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

func (_mr *_MockNotifierInterfaceRecorder) NotifyWithData(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NotifyWithData", arg0, arg1, arg2)
}
