package types

import (
	"kego.io/selectors/tests"
	"kego.io/system"
	_ "kego.io/system/types"
)

func init() {
	ptr0 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@basic"}
	ptr1 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr2 := &system.Object{Description: "Automatically created basic rule for basic", Id: ptr0, Rules: []system.RuleInterface(nil), Type: ptr1}
	ptr3 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr4 := system.String("object")
	ptr5 := &system.Type{Object: ptr2, Embed: []*system.Reference{ptr3}, Fields: map[string]system.RuleInterface(nil), Native: &ptr4, Rule: (*system.Type)(nil)}
	ptr6 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@c"}
	ptr7 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr8 := &system.Object{Description: "Automatically created basic rule for c", Id: ptr6, Rules: []system.RuleInterface(nil), Type: ptr7}
	ptr9 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr10 := system.String("object")
	ptr11 := &system.Type{Object: ptr8, Embed: []*system.Reference{ptr9}, Fields: map[string]system.RuleInterface(nil), Native: &ptr10, Rule: (*system.Type)(nil)}
	ptr12 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@collision"}
	ptr13 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr14 := &system.Object{Description: "Automatically created basic rule for collision", Id: ptr12, Rules: []system.RuleInterface(nil), Type: ptr13}
	ptr15 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr16 := system.String("object")
	ptr17 := &system.Type{Object: ptr14, Embed: []*system.Reference{ptr15}, Fields: map[string]system.RuleInterface(nil), Native: &ptr16, Rule: (*system.Type)(nil)}
	ptr18 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@diagram"}
	ptr19 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr20 := &system.Object{Description: "Automatically created basic rule for diagram", Id: ptr18, Rules: []system.RuleInterface(nil), Type: ptr19}
	ptr21 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr22 := system.String("object")
	ptr23 := &system.Type{Object: ptr20, Embed: []*system.Reference{ptr21}, Fields: map[string]system.RuleInterface(nil), Native: &ptr22, Rule: (*system.Type)(nil)}
	ptr24 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@expr"}
	ptr25 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr26 := &system.Object{Description: "Automatically created basic rule for expr", Id: ptr24, Rules: []system.RuleInterface(nil), Type: ptr25}
	ptr27 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr28 := system.String("object")
	ptr29 := &system.Type{Object: ptr26, Embed: []*system.Reference{ptr27}, Fields: map[string]system.RuleInterface(nil), Native: &ptr28, Rule: (*system.Type)(nil)}
	ptr30 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@gallery"}
	ptr31 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr32 := &system.Object{Description: "Automatically created basic rule for gallery", Id: ptr30, Rules: []system.RuleInterface(nil), Type: ptr31}
	ptr33 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr34 := system.String("object")
	ptr35 := &system.Type{Object: ptr32, Embed: []*system.Reference{ptr33}, Fields: map[string]system.RuleInterface(nil), Native: &ptr34, Rule: (*system.Type)(nil)}
	ptr36 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr37 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr38 := &system.Object{Description: "Automatically created basic rule for image", Id: ptr36, Rules: []system.RuleInterface(nil), Type: ptr37}
	ptr39 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr40 := system.String("object")
	ptr41 := &system.Type{Object: ptr38, Embed: []*system.Reference{ptr39}, Fields: map[string]system.RuleInterface(nil), Native: &ptr40, Rule: (*system.Type)(nil)}
	ptr42 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instance"}
	ptr43 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr44 := &system.Object{Description: "Automatically created basic rule for instance", Id: ptr42, Rules: []system.RuleInterface(nil), Type: ptr43}
	ptr45 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr46 := system.String("object")
	ptr47 := &system.Type{Object: ptr44, Embed: []*system.Reference{ptr45}, Fields: map[string]system.RuleInterface(nil), Native: &ptr46, Rule: (*system.Type)(nil)}
	ptr48 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr49 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr50 := &system.Object{Description: "Automatically created basic rule for instanceItem", Id: ptr48, Rules: []system.RuleInterface(nil), Type: ptr49}
	ptr51 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr52 := system.String("object")
	ptr53 := &system.Type{Object: ptr50, Embed: []*system.Reference{ptr51}, Fields: map[string]system.RuleInterface(nil), Native: &ptr52, Rule: (*system.Type)(nil)}
	ptr54 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr55 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr56 := &system.Object{Description: "Automatically created basic rule for kid", Id: ptr54, Rules: []system.RuleInterface(nil), Type: ptr55}
	ptr57 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr58 := system.String("object")
	ptr59 := &system.Type{Object: ptr56, Embed: []*system.Reference{ptr57}, Fields: map[string]system.RuleInterface(nil), Native: &ptr58, Rule: (*system.Type)(nil)}
	ptr60 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@photo"}
	ptr61 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr62 := &system.Object{Description: "Automatically created basic rule for photo", Id: ptr60, Rules: []system.RuleInterface(nil), Type: ptr61}
	ptr63 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr64 := system.String("object")
	ptr65 := &system.Type{Object: ptr62, Embed: []*system.Reference{ptr63}, Fields: map[string]system.RuleInterface(nil), Native: &ptr64, Rule: (*system.Type)(nil)}
	ptr66 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@polykids"}
	ptr67 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr68 := &system.Object{Description: "Automatically created basic rule for polykids", Id: ptr66, Rules: []system.RuleInterface(nil), Type: ptr67}
	ptr69 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr70 := system.String("object")
	ptr71 := &system.Type{Object: ptr68, Embed: []*system.Reference{ptr69}, Fields: map[string]system.RuleInterface(nil), Native: &ptr70, Rule: (*system.Type)(nil)}
	ptr72 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rectangle"}
	ptr73 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr74 := &system.Object{Description: "Automatically created basic rule for rectangle", Id: ptr72, Rules: []system.RuleInterface(nil), Type: ptr73}
	ptr75 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr76 := system.String("object")
	ptr77 := &system.Type{Object: ptr74, Embed: []*system.Reference{ptr75}, Fields: map[string]system.RuleInterface(nil), Native: &ptr76, Rule: (*system.Type)(nil)}
	ptr78 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscale"}
	ptr79 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr80 := &system.Object{Description: "Automatically created basic rule for rightscale", Id: ptr78, Rules: []system.RuleInterface(nil), Type: ptr79}
	ptr81 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr82 := system.String("object")
	ptr83 := &system.Type{Object: ptr80, Embed: []*system.Reference{ptr81}, Fields: map[string]system.RuleInterface(nil), Native: &ptr82, Rule: (*system.Type)(nil)}
	ptr84 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr85 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr86 := &system.Object{Description: "Automatically created basic rule for rightscaleLink", Id: ptr84, Rules: []system.RuleInterface(nil), Type: ptr85}
	ptr87 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr88 := system.String("object")
	ptr89 := &system.Type{Object: ptr86, Embed: []*system.Reference{ptr87}, Fields: map[string]system.RuleInterface(nil), Native: &ptr88, Rule: (*system.Type)(nil)}
	ptr90 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleList"}
	ptr91 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr92 := &system.Object{Description: "Automatically created basic rule for rightscaleList", Id: ptr90, Rules: []system.RuleInterface(nil), Type: ptr91}
	ptr93 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr94 := system.String("object")
	ptr95 := &system.Type{Object: ptr92, Embed: []*system.Reference{ptr93}, Fields: map[string]system.RuleInterface(nil), Native: &ptr94, Rule: (*system.Type)(nil)}
	ptr96 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@sibling"}
	ptr97 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr98 := &system.Object{Description: "Automatically created basic rule for sibling", Id: ptr96, Rules: []system.RuleInterface(nil), Type: ptr97}
	ptr99 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr100 := system.String("object")
	ptr101 := &system.Type{Object: ptr98, Embed: []*system.Reference{ptr99}, Fields: map[string]system.RuleInterface(nil), Native: &ptr100, Rule: (*system.Type)(nil)}
	ptr102 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simple"}
	ptr103 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr104 := &system.Object{Description: "Automatically created basic rule for simple", Id: ptr102, Rules: []system.RuleInterface(nil), Type: ptr103}
	ptr105 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr106 := system.String("object")
	ptr107 := &system.Type{Object: ptr104, Embed: []*system.Reference{ptr105}, Fields: map[string]system.RuleInterface(nil), Native: &ptr106, Rule: (*system.Type)(nil)}
	ptr108 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simpleItem"}
	ptr109 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr110 := &system.Object{Description: "Automatically created basic rule for simpleItem", Id: ptr108, Rules: []system.RuleInterface(nil), Type: ptr109}
	ptr111 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr112 := system.String("object")
	ptr113 := &system.Type{Object: ptr110, Embed: []*system.Reference{ptr111}, Fields: map[string]system.RuleInterface(nil), Native: &ptr112, Rule: (*system.Type)(nil)}
	ptr114 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@typed"}
	ptr115 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr116 := &system.Object{Description: "Automatically created basic rule for typed", Id: ptr114, Rules: []system.RuleInterface(nil), Type: ptr115}
	ptr117 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr118 := system.String("object")
	ptr119 := &system.Type{Object: ptr116, Embed: []*system.Reference{ptr117}, Fields: map[string]system.RuleInterface(nil), Native: &ptr118, Rule: (*system.Type)(nil)}
	ptr120 := &system.Reference{Package: "kego.io/selectors/tests", Name: "basic"}
	ptr121 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr122 := &system.Object{Id: ptr120, Rules: []system.RuleInterface(nil), Type: ptr121}
	ptr123 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr124 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr123}
	ptr125 := &system.Rule{}
	ptr126 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr127 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr126}
	ptr128 := &system.Rule{}
	ptr129 := &system.StringRule{Object: ptr127, Rule: ptr128, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr130 := &system.ArrayRule{Object: ptr124, Rule: ptr125, Items: ptr129, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr131 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr132 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr131}
	ptr133 := &system.Rule{}
	ptr134 := &system.StringRule{Object: ptr132, Rule: ptr133, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr135 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr136 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr135}
	ptr137 := &system.Rule{}
	ptr138 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr139 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr138}
	ptr140 := &system.Rule{}
	ptr141 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr142 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr141}
	ptr143 := &system.Rule{}
	ptr144 := &system.StringRule{Object: ptr142, Rule: ptr143, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr145 := &system.MapRule{Object: ptr139, Rule: ptr140, Items: ptr144, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr146 := &system.ArrayRule{Object: ptr136, Rule: ptr137, Items: ptr145, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr147 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr148 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr147}
	ptr149 := &system.Rule{}
	ptr150 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr151 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr150}
	ptr152 := &system.Rule{}
	ptr153 := &system.StringRule{Object: ptr151, Rule: ptr152, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr154 := &system.MapRule{Object: ptr148, Rule: ptr149, Items: ptr153, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr155 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr156 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr155}
	ptr157 := &system.Rule{}
	ptr158 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr159 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr158}
	ptr160 := &system.Rule{}
	ptr161 := &system.StringRule{Object: ptr159, Rule: ptr160, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr162 := &system.ArrayRule{Object: ptr156, Rule: ptr157, Items: ptr161, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr163 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr164 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr163}
	ptr165 := &system.Rule{}
	ptr166 := &system.NumberRule{Object: ptr164, Rule: ptr165, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr167 := system.String("object")
	ptr168 := &system.Type{Object: ptr122, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"drinkPreference": ptr130, "favoriteColor": ptr134, "languagesSpoken": ptr146, "name": ptr154, "seatingPreference": ptr162, "weight": ptr166}, Native: &ptr167, Rule: (*system.Type)(nil)}
	ptr169 := &system.Reference{Package: "kego.io/selectors/tests", Name: "c"}
	ptr170 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr171 := &system.Object{Id: ptr169, Rules: []system.RuleInterface(nil), Type: ptr170}
	ptr172 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr173 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr172}
	ptr174 := &system.Rule{}
	ptr175 := &system.NumberRule{Object: ptr173, Rule: ptr174, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr176 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr177 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr176}
	ptr178 := &system.Rule{}
	ptr179 := &system.NumberRule{Object: ptr177, Rule: ptr178, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr180 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr181 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr180}
	ptr182 := &system.Rule{}
	ptr183 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr184 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr183}
	ptr185 := &system.Rule{}
	ptr186 := &system.NumberRule{Object: ptr184, Rule: ptr185, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr187 := &system.MapRule{Object: ptr181, Rule: ptr182, Items: ptr186, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr188 := system.String("object")
	ptr189 := &system.Type{Object: ptr171, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr175, "b": ptr179, "c": ptr187}, Native: &ptr188, Rule: (*system.Type)(nil)}
	ptr190 := &system.Reference{Package: "kego.io/selectors/tests", Name: "collision"}
	ptr191 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr192 := &system.Object{Id: ptr190, Rules: []system.RuleInterface(nil), Type: ptr191}
	ptr193 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr194 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr193}
	ptr195 := &system.Rule{}
	ptr196 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr197 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr196}
	ptr198 := &system.Rule{}
	ptr199 := &system.StringRule{Object: ptr197, Rule: ptr198, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr200 := &system.MapRule{Object: ptr194, Rule: ptr195, Items: ptr199, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr201 := system.String("object")
	ptr202 := &system.Type{Object: ptr192, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"number": ptr200}, Native: &ptr201, Rule: (*system.Type)(nil)}
	ptr203 := &system.Reference{Package: "kego.io/selectors/tests", Name: "diagram"}
	ptr204 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr205 := &system.Object{Id: ptr203, Rules: []system.RuleInterface(nil), Type: ptr204}
	ptr206 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr207 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr206}
	ptr208 := &system.Rule{}
	ptr209 := &system.StringRule{Object: ptr207, Rule: ptr208, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr210 := system.String("object")
	ptr211 := &system.Type{Object: ptr205, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"url": ptr209}, Native: &ptr210, Rule: (*system.Type)(nil)}
	ptr212 := &system.Reference{Package: "kego.io/selectors/tests", Name: "expr"}
	ptr213 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr214 := &system.Object{Id: ptr212, Rules: []system.RuleInterface(nil), Type: ptr213}
	ptr215 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr216 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr215}
	ptr217 := &system.Rule{}
	ptr218 := &system.BoolRule{Object: ptr216, Rule: ptr217, Default: (*system.Bool)(nil)}
	ptr219 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr220 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr219}
	ptr221 := &system.Rule{}
	ptr222 := &system.NumberRule{Object: ptr220, Rule: ptr221, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr223 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr224 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr223}
	ptr225 := &system.Rule{}
	ptr226 := &system.NumberRule{Object: ptr224, Rule: ptr225, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr227 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr228 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr227}
	ptr229 := &system.Rule{}
	ptr230 := &system.StringRule{Object: ptr228, Rule: ptr229, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr231 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr232 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr231}
	ptr233 := &system.Rule{}
	ptr234 := &system.StringRule{Object: ptr232, Rule: ptr233, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr235 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr236 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr235}
	ptr237 := &system.Rule{}
	ptr238 := &system.StringRule{Object: ptr236, Rule: ptr237, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr239 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr240 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr239}
	ptr241 := &system.Rule{}
	ptr242 := &system.BoolRule{Object: ptr240, Rule: ptr241, Default: (*system.Bool)(nil)}
	ptr243 := system.String("object")
	ptr244 := &system.Type{Object: ptr214, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"false": ptr218, "float": ptr222, "int": ptr226, "null": ptr230, "string": ptr234, "string2": ptr238, "true": ptr242}, Native: &ptr243, Rule: (*system.Type)(nil)}
	ptr245 := &system.Reference{Package: "kego.io/selectors/tests", Name: "gallery"}
	ptr246 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr247 := &system.Object{Description: "This represents a gallery - it's just a list of images", Id: ptr245, Rules: []system.RuleInterface(nil), Type: ptr246}
	ptr248 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr249 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr248}
	ptr250 := &system.Rule{}
	ptr251 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr252 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr251}
	ptr253 := &system.Rule{}
	ptr254 := &tests.ImageRule{Object: ptr252, Rule: ptr253}
	ptr255 := &system.MapRule{Object: ptr249, Rule: ptr250, Items: ptr254, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr256 := system.String("object")
	ptr257 := &system.Type{Object: ptr247, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"images": ptr255}, Native: &ptr256, Rule: (*system.Type)(nil)}
	ptr258 := &system.Reference{Package: "kego.io/selectors/tests", Name: "image"}
	ptr259 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr260 := &system.Object{Id: ptr258, Rules: []system.RuleInterface(nil), Type: ptr259}
	ptr261 := system.String("object")
	ptr262 := &system.Type{Object: ptr260, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Interface: true, Native: &ptr261, Rule: (*system.Type)(nil)}
	ptr263 := &system.Reference{Package: "kego.io/selectors/tests", Name: "instance"}
	ptr264 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr265 := &system.Object{Id: ptr263, Rules: []system.RuleInterface(nil), Type: ptr264}
	ptr266 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr267 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr266}
	ptr268 := &system.Rule{}
	ptr269 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr270 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr269}
	ptr271 := &system.Rule{}
	ptr272 := &tests.InstanceItemRule{Object: ptr270, Rule: ptr271}
	ptr273 := &system.MapRule{Object: ptr267, Rule: ptr268, Items: ptr272, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr274 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr275 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr274}
	ptr276 := &system.Rule{}
	ptr277 := &system.StringRule{Object: ptr275, Rule: ptr276, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr278 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr279 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr278}
	ptr280 := &system.Rule{}
	ptr281 := &system.StringRule{Object: ptr279, Rule: ptr280, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr282 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr283 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr282}
	ptr284 := &system.Rule{}
	ptr285 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr286 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr285}
	ptr287 := &system.Rule{}
	ptr288 := &tests.RightscaleLinkRule{Object: ptr286, Rule: ptr287}
	ptr289 := &system.ArrayRule{Object: ptr283, Rule: ptr284, Items: ptr288, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr290 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr291 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr290}
	ptr292 := &system.Rule{}
	ptr293 := &system.StringRule{Object: ptr291, Rule: ptr292, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr294 := system.String("object")
	ptr295 := &system.Type{Object: ptr265, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"child": ptr273, "cloud_type": ptr277, "display_name": ptr281, "links": ptr289, "name": ptr293}, Native: &ptr294, Rule: (*system.Type)(nil)}
	ptr296 := &system.Reference{Package: "kego.io/selectors/tests", Name: "instanceItem"}
	ptr297 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr298 := &system.Object{Id: ptr296, Rules: []system.RuleInterface(nil), Type: ptr297}
	ptr299 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr300 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr299}
	ptr301 := &system.Rule{}
	ptr302 := &system.StringRule{Object: ptr300, Rule: ptr301, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr303 := system.String("object")
	ptr304 := &system.Type{Object: ptr298, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"name": ptr302}, Native: &ptr303, Rule: (*system.Type)(nil)}
	ptr305 := &system.Reference{Package: "kego.io/selectors/tests", Name: "kid"}
	ptr306 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr307 := &system.Object{Id: ptr305, Rules: []system.RuleInterface(nil), Type: ptr306}
	ptr308 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr309 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr308}
	ptr310 := &system.Rule{}
	ptr311 := &system.StringRule{Object: ptr309, Rule: ptr310, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr312 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr313 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr312}
	ptr314 := &system.Rule{}
	ptr315 := &system.StringRule{Object: ptr313, Rule: ptr314, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr316 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr317 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr316}
	ptr318 := &system.Rule{Optional: true}
	ptr319 := &system.BoolRule{Object: ptr317, Rule: ptr318, Default: (*system.Bool)(nil)}
	ptr320 := system.String("object")
	ptr321 := &system.Type{Object: ptr307, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"language": ptr311, "level": ptr315, "preferred": ptr319}, Native: &ptr320, Rule: (*system.Type)(nil)}
	ptr322 := &system.Reference{Package: "kego.io/selectors/tests", Name: "photo"}
	ptr323 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr324 := &system.Object{Description: "This represents an image, and contains path, server and protocol separately", Id: ptr322, Rules: []system.RuleInterface(nil), Type: ptr323}
	ptr325 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr326 := &system.Object{Description: "The path for the url - e.g. /foo/bar.jpg", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr325}
	ptr327 := &system.Rule{}
	ptr328 := &system.StringRule{Object: ptr326, Rule: ptr327, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr329 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr330 := &system.Object{Description: "The protocol for the url - e.g. http or https", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr329}
	ptr331 := &system.Rule{Optional: true}
	ptr332 := system.String("http")
	ptr333 := &system.StringRule{Object: ptr330, Rule: ptr331, Default: &ptr332, Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr334 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr335 := &system.Object{Description: "The server for the url - e.g. www.google.com", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr334}
	ptr336 := &system.Rule{}
	ptr337 := &system.StringRule{Object: ptr335, Rule: ptr336, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr338 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rectangle"}
	ptr339 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr338}
	ptr340 := &system.Rule{Optional: true}
	ptr341 := &tests.RectangleRule{Object: ptr339, Rule: ptr340}
	ptr342 := system.String("object")
	ptr343 := &system.Type{Object: ptr324, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"path": ptr328, "protocol": ptr333, "server": ptr337, "size": ptr341}, Native: &ptr342, Rule: (*system.Type)(nil)}
	ptr344 := &system.Reference{Package: "kego.io/selectors/tests", Name: "polykids"}
	ptr345 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr346 := &system.Object{Id: ptr344, Rules: []system.RuleInterface(nil), Type: ptr345}
	ptr347 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr348 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr347}
	ptr349 := &system.Rule{}
	ptr350 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr351 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr350}
	ptr352 := &system.Rule{}
	ptr353 := &tests.KidRule{Object: ptr351, Rule: ptr352}
	ptr354 := &system.ArrayRule{Object: ptr348, Rule: ptr349, Items: ptr353, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr355 := system.String("object")
	ptr356 := &system.Type{Object: ptr346, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr354}, Native: &ptr355, Rule: (*system.Type)(nil)}
	ptr357 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rectangle"}
	ptr358 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr359 := &system.Object{Id: ptr357, Rules: []system.RuleInterface(nil), Type: ptr358}
	ptr360 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr361 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr360}
	ptr362 := &system.Rule{}
	ptr363 := &system.IntRule{Object: ptr361, Rule: ptr362, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr364 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr365 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr364}
	ptr366 := &system.Rule{}
	ptr367 := &system.IntRule{Object: ptr365, Rule: ptr366, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr368 := system.String("object")
	ptr369 := &system.Type{Object: ptr359, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"height": ptr363, "width": ptr367}, Native: &ptr368, Rule: (*system.Type)(nil)}
	ptr370 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscale"}
	ptr371 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr372 := &system.Object{Id: ptr370, Rules: []system.RuleInterface(nil), Type: ptr371}
	ptr373 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr374 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr373}
	ptr375 := &system.Rule{}
	ptr376 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr377 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr376}
	ptr378 := &system.Rule{}
	ptr379 := &tests.InstanceItemRule{Object: ptr377, Rule: ptr378}
	ptr380 := &system.MapRule{Object: ptr374, Rule: ptr375, Items: ptr379, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr381 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr382 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr381}
	ptr383 := &system.Rule{}
	ptr384 := &system.StringRule{Object: ptr382, Rule: ptr383, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr385 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr386 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr385}
	ptr387 := &system.Rule{}
	ptr388 := &system.StringRule{Object: ptr386, Rule: ptr387, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr389 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr390 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr389}
	ptr391 := &system.Rule{}
	ptr392 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr393 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr392}
	ptr394 := &system.Rule{}
	ptr395 := &tests.RightscaleLinkRule{Object: ptr393, Rule: ptr394}
	ptr396 := &system.ArrayRule{Object: ptr390, Rule: ptr391, Items: ptr395, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr397 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr398 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr397}
	ptr399 := &system.Rule{}
	ptr400 := &system.StringRule{Object: ptr398, Rule: ptr399, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr401 := system.String("object")
	ptr402 := &system.Type{Object: ptr372, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"child": ptr380, "cloud_type": ptr384, "display_name": ptr388, "links": ptr396, "name": ptr400}, Native: &ptr401, Rule: (*system.Type)(nil)}
	ptr403 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscaleLink"}
	ptr404 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr405 := &system.Object{Id: ptr403, Rules: []system.RuleInterface(nil), Type: ptr404}
	ptr406 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr407 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr406}
	ptr408 := &system.Rule{}
	ptr409 := &system.StringRule{Object: ptr407, Rule: ptr408, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr410 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr411 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr410}
	ptr412 := &system.Rule{}
	ptr413 := &system.StringRule{Object: ptr411, Rule: ptr412, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr414 := system.String("object")
	ptr415 := &system.Type{Object: ptr405, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"href": ptr409, "rel": ptr413}, Native: &ptr414, Rule: (*system.Type)(nil)}
	ptr416 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscaleList"}
	ptr417 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr418 := &system.Object{Id: ptr416, Rules: []system.RuleInterface(nil), Type: ptr417}
	ptr419 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr420 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr419}
	ptr421 := &system.Rule{}
	ptr422 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscale"}
	ptr423 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr422}
	ptr424 := &system.Rule{}
	ptr425 := &tests.RightscaleRule{Object: ptr423, Rule: ptr424}
	ptr426 := &system.ArrayRule{Object: ptr420, Rule: ptr421, Items: ptr425, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr427 := system.String("object")
	ptr428 := &system.Type{Object: ptr418, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"foo": ptr426}, Native: &ptr427, Rule: (*system.Type)(nil)}
	ptr429 := &system.Reference{Package: "kego.io/selectors/tests", Name: "sibling"}
	ptr430 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr431 := &system.Object{Id: ptr429, Rules: []system.RuleInterface(nil), Type: ptr430}
	ptr432 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr433 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr432}
	ptr434 := &system.Rule{}
	ptr435 := &system.NumberRule{Object: ptr433, Rule: ptr434, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr436 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr437 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr436}
	ptr438 := &system.Rule{}
	ptr439 := &system.NumberRule{Object: ptr437, Rule: ptr438, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr440 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@c"}
	ptr441 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr440}
	ptr442 := &system.Rule{}
	ptr443 := &tests.CRule{Object: ptr441, Rule: ptr442}
	ptr444 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr445 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr444}
	ptr446 := &system.Rule{}
	ptr447 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr448 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr447}
	ptr449 := &system.Rule{}
	ptr450 := &system.NumberRule{Object: ptr448, Rule: ptr449, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr451 := &system.MapRule{Object: ptr445, Rule: ptr446, Items: ptr450, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr452 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr453 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr452}
	ptr454 := &system.Rule{}
	ptr455 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr456 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr455}
	ptr457 := &system.Rule{}
	ptr458 := &system.NumberRule{Object: ptr456, Rule: ptr457, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr459 := &system.MapRule{Object: ptr453, Rule: ptr454, Items: ptr458, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr460 := system.String("object")
	ptr461 := &system.Type{Object: ptr431, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr435, "b": ptr439, "c": ptr443, "d": ptr451, "e": ptr459}, Native: &ptr460, Rule: (*system.Type)(nil)}
	ptr462 := &system.Reference{Package: "kego.io/selectors/tests", Name: "simple"}
	ptr463 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr464 := &system.Object{Id: ptr462, Rules: []system.RuleInterface(nil), Type: ptr463}
	ptr465 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simpleItem"}
	ptr466 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr465}
	ptr467 := &system.Rule{}
	ptr468 := &tests.SimpleItemRule{Object: ptr466, Rule: ptr467}
	ptr469 := system.String("object")
	ptr470 := &system.Type{Object: ptr464, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr468}, Native: &ptr469, Rule: (*system.Type)(nil)}
	ptr471 := &system.Reference{Package: "kego.io/selectors/tests", Name: "simpleItem"}
	ptr472 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr473 := &system.Object{Id: ptr471, Rules: []system.RuleInterface(nil), Type: ptr472}
	ptr474 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr475 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr474}
	ptr476 := &system.Rule{}
	ptr477 := &system.StringRule{Object: ptr475, Rule: ptr476, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr478 := system.String("object")
	ptr479 := &system.Type{Object: ptr473, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"b": ptr477}, Native: &ptr478, Rule: (*system.Type)(nil)}
	ptr480 := &system.Reference{Package: "kego.io/selectors/tests", Name: "typed"}
	ptr481 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr482 := &system.Object{Id: ptr480, Rules: []system.RuleInterface(nil), Type: ptr481}
	ptr483 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr484 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr483}
	ptr485 := &system.Rule{}
	ptr486 := &tests.ImageRule{Object: ptr484, Rule: ptr485}
	ptr487 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr488 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr487}
	ptr489 := &system.Rule{}
	ptr490 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr491 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr490}
	ptr492 := &system.Rule{}
	ptr493 := &system.StringRule{Object: ptr491, Rule: ptr492, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr494 := &system.ArrayRule{Object: ptr488, Rule: ptr489, Items: ptr493, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr495 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr496 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr495}
	ptr497 := &system.Rule{}
	ptr498 := &system.StringRule{Object: ptr496, Rule: ptr497, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr499 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr500 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr499}
	ptr501 := &system.Rule{}
	ptr502 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr503 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr502}
	ptr504 := &system.Rule{}
	ptr505 := &tests.KidRule{Object: ptr503, Rule: ptr504}
	ptr506 := &system.MapRule{Object: ptr500, Rule: ptr501, Items: ptr505, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr507 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr508 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr507}
	ptr509 := &system.Rule{}
	ptr510 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr511 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr510}
	ptr512 := &system.Rule{}
	ptr513 := &system.StringRule{Object: ptr511, Rule: ptr512, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr514 := &system.MapRule{Object: ptr508, Rule: ptr509, Items: ptr513, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr515 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr516 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr515}
	ptr517 := &system.Rule{}
	ptr518 := &system.NumberRule{Object: ptr516, Rule: ptr517, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr519 := system.String("object")
	ptr520 := &system.Type{Object: ptr482, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"avatar": ptr486, "drinkPreference": ptr494, "favoriteColor": ptr498, "kids": ptr506, "name": ptr514, "weight": ptr518}, Native: &ptr519, Rule: (*system.Type)(nil)}
	system.Register("kego.io/selectors/tests", "@basic", ptr5, 0xe2f725e9d48b69d4)
	system.Register("kego.io/selectors/tests", "@c", ptr11, 0x6a4bf0b03046c68a)
	system.Register("kego.io/selectors/tests", "@collision", ptr17, 0x2f6382cf84b27ee7)
	system.Register("kego.io/selectors/tests", "@diagram", ptr23, 0xe436ca2eaee25542)
	system.Register("kego.io/selectors/tests", "@expr", ptr29, 0x6214e678b1df35e3)
	system.Register("kego.io/selectors/tests", "@gallery", ptr35, 0xa2261dbb985b3d3)
	system.Register("kego.io/selectors/tests", "@image", ptr41, 0x2a2a6f416ac31013)
	system.Register("kego.io/selectors/tests", "@instance", ptr47, 0xa7637e9d5bf458e9)
	system.Register("kego.io/selectors/tests", "@instanceItem", ptr53, 0x2dca71ec3918c621)
	system.Register("kego.io/selectors/tests", "@kid", ptr59, 0x3b576fd38b04a2eb)
	system.Register("kego.io/selectors/tests", "@photo", ptr65, 0xac9c6abe1bbdc4f4)
	system.Register("kego.io/selectors/tests", "@polykids", ptr71, 0xebaffecb552df4d1)
	system.Register("kego.io/selectors/tests", "@rectangle", ptr77, 0x21539507256190ab)
	system.Register("kego.io/selectors/tests", "@rightscale", ptr83, 0xde456fd6916c6f51)
	system.Register("kego.io/selectors/tests", "@rightscaleLink", ptr89, 0x127d9489c45697ea)
	system.Register("kego.io/selectors/tests", "@rightscaleList", ptr95, 0x6a9527067852e20b)
	system.Register("kego.io/selectors/tests", "@sibling", ptr101, 0xac837d672ff74ed6)
	system.Register("kego.io/selectors/tests", "@simple", ptr107, 0x7054dc6469f4db46)
	system.Register("kego.io/selectors/tests", "@simpleItem", ptr113, 0xac167d73687ccb1f)
	system.Register("kego.io/selectors/tests", "@typed", ptr119, 0x216d0e1d4c22bb2d)
	system.Register("kego.io/selectors/tests", "basic", ptr168, 0xe2f725e9d48b69d4)
	system.Register("kego.io/selectors/tests", "c", ptr189, 0x6a4bf0b03046c68a)
	system.Register("kego.io/selectors/tests", "collision", ptr202, 0x2f6382cf84b27ee7)
	system.Register("kego.io/selectors/tests", "diagram", ptr211, 0xe436ca2eaee25542)
	system.Register("kego.io/selectors/tests", "expr", ptr244, 0x6214e678b1df35e3)
	system.Register("kego.io/selectors/tests", "gallery", ptr257, 0xa2261dbb985b3d3)
	system.Register("kego.io/selectors/tests", "image", ptr262, 0x2a2a6f416ac31013)
	system.Register("kego.io/selectors/tests", "instance", ptr295, 0xa7637e9d5bf458e9)
	system.Register("kego.io/selectors/tests", "instanceItem", ptr304, 0x2dca71ec3918c621)
	system.Register("kego.io/selectors/tests", "kid", ptr321, 0x3b576fd38b04a2eb)
	system.Register("kego.io/selectors/tests", "photo", ptr343, 0xac9c6abe1bbdc4f4)
	system.Register("kego.io/selectors/tests", "polykids", ptr356, 0xebaffecb552df4d1)
	system.Register("kego.io/selectors/tests", "rectangle", ptr369, 0x21539507256190ab)
	system.Register("kego.io/selectors/tests", "rightscale", ptr402, 0xde456fd6916c6f51)
	system.Register("kego.io/selectors/tests", "rightscaleLink", ptr415, 0x127d9489c45697ea)
	system.Register("kego.io/selectors/tests", "rightscaleList", ptr428, 0x6a9527067852e20b)
	system.Register("kego.io/selectors/tests", "sibling", ptr461, 0xac837d672ff74ed6)
	system.Register("kego.io/selectors/tests", "simple", ptr470, 0x7054dc6469f4db46)
	system.Register("kego.io/selectors/tests", "simpleItem", ptr479, 0xac167d73687ccb1f)
	system.Register("kego.io/selectors/tests", "typed", ptr520, 0x216d0e1d4c22bb2d)
}
