package types

import (
	"kego.io/selectors/tests"
	"kego.io/system"
	_ "kego.io/system/types"
)

func init() {
	ptr0 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@basic"}
	ptr1 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr2 := &system.Object{Description: "Automatically created basic rule for basic", Id: ptr0, Rules: []system.RuleInterface(nil), Type: ptr1}
	ptr3 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr4 := system.String("object")
	ptr5 := &system.Type{Object: ptr2, Embed: []*system.Reference{ptr3}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr4, Rule: (*system.Type)(nil)}
	ptr6 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@c"}
	ptr7 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr8 := &system.Object{Description: "Automatically created basic rule for c", Id: ptr6, Rules: []system.RuleInterface(nil), Type: ptr7}
	ptr9 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr10 := system.String("object")
	ptr11 := &system.Type{Object: ptr8, Embed: []*system.Reference{ptr9}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr10, Rule: (*system.Type)(nil)}
	ptr12 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@collision"}
	ptr13 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr14 := &system.Object{Description: "Automatically created basic rule for collision", Id: ptr12, Rules: []system.RuleInterface(nil), Type: ptr13}
	ptr15 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr16 := system.String("object")
	ptr17 := &system.Type{Object: ptr14, Embed: []*system.Reference{ptr15}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr16, Rule: (*system.Type)(nil)}
	ptr18 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@diagram"}
	ptr19 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr20 := &system.Object{Description: "Automatically created basic rule for diagram", Id: ptr18, Rules: []system.RuleInterface(nil), Type: ptr19}
	ptr21 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr22 := system.String("object")
	ptr23 := &system.Type{Object: ptr20, Embed: []*system.Reference{ptr21}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr22, Rule: (*system.Type)(nil)}
	ptr24 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@expr"}
	ptr25 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr26 := &system.Object{Description: "Automatically created basic rule for expr", Id: ptr24, Rules: []system.RuleInterface(nil), Type: ptr25}
	ptr27 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr28 := system.String("object")
	ptr29 := &system.Type{Object: ptr26, Embed: []*system.Reference{ptr27}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr28, Rule: (*system.Type)(nil)}
	ptr30 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@gallery"}
	ptr31 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr32 := &system.Object{Description: "Automatically created basic rule for gallery", Id: ptr30, Rules: []system.RuleInterface(nil), Type: ptr31}
	ptr33 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr34 := system.String("object")
	ptr35 := &system.Type{Object: ptr32, Embed: []*system.Reference{ptr33}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr34, Rule: (*system.Type)(nil)}
	ptr36 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr37 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr38 := &system.Object{Description: "Automatically created basic rule for image", Id: ptr36, Rules: []system.RuleInterface(nil), Type: ptr37}
	ptr39 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr40 := system.String("object")
	ptr41 := &system.Type{Object: ptr38, Embed: []*system.Reference{ptr39}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr40, Rule: (*system.Type)(nil)}
	ptr42 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instance"}
	ptr43 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr44 := &system.Object{Description: "Automatically created basic rule for instance", Id: ptr42, Rules: []system.RuleInterface(nil), Type: ptr43}
	ptr45 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr46 := system.String("object")
	ptr47 := &system.Type{Object: ptr44, Embed: []*system.Reference{ptr45}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr46, Rule: (*system.Type)(nil)}
	ptr48 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr49 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr50 := &system.Object{Description: "Automatically created basic rule for instanceItem", Id: ptr48, Rules: []system.RuleInterface(nil), Type: ptr49}
	ptr51 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr52 := system.String("object")
	ptr53 := &system.Type{Object: ptr50, Embed: []*system.Reference{ptr51}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr52, Rule: (*system.Type)(nil)}
	ptr54 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr55 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr56 := &system.Object{Description: "Automatically created basic rule for kid", Id: ptr54, Rules: []system.RuleInterface(nil), Type: ptr55}
	ptr57 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr58 := system.String("object")
	ptr59 := &system.Type{Object: ptr56, Embed: []*system.Reference{ptr57}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr58, Rule: (*system.Type)(nil)}
	ptr60 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@photo"}
	ptr61 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr62 := &system.Object{Description: "Automatically created basic rule for photo", Id: ptr60, Rules: []system.RuleInterface(nil), Type: ptr61}
	ptr63 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr64 := system.String("object")
	ptr65 := &system.Type{Object: ptr62, Embed: []*system.Reference{ptr63}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr64, Rule: (*system.Type)(nil)}
	ptr66 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@polykids"}
	ptr67 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr68 := &system.Object{Description: "Automatically created basic rule for polykids", Id: ptr66, Rules: []system.RuleInterface(nil), Type: ptr67}
	ptr69 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr70 := system.String("object")
	ptr71 := &system.Type{Object: ptr68, Embed: []*system.Reference{ptr69}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr70, Rule: (*system.Type)(nil)}
	ptr72 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rectangle"}
	ptr73 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr74 := &system.Object{Description: "Automatically created basic rule for rectangle", Id: ptr72, Rules: []system.RuleInterface(nil), Type: ptr73}
	ptr75 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr76 := system.String("object")
	ptr77 := &system.Type{Object: ptr74, Embed: []*system.Reference{ptr75}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr76, Rule: (*system.Type)(nil)}
	ptr78 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscale"}
	ptr79 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr80 := &system.Object{Description: "Automatically created basic rule for rightscale", Id: ptr78, Rules: []system.RuleInterface(nil), Type: ptr79}
	ptr81 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr82 := system.String("object")
	ptr83 := &system.Type{Object: ptr80, Embed: []*system.Reference{ptr81}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr82, Rule: (*system.Type)(nil)}
	ptr84 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr85 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr86 := &system.Object{Description: "Automatically created basic rule for rightscaleLink", Id: ptr84, Rules: []system.RuleInterface(nil), Type: ptr85}
	ptr87 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr88 := system.String("object")
	ptr89 := &system.Type{Object: ptr86, Embed: []*system.Reference{ptr87}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr88, Rule: (*system.Type)(nil)}
	ptr90 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleList"}
	ptr91 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr92 := &system.Object{Description: "Automatically created basic rule for rightscaleList", Id: ptr90, Rules: []system.RuleInterface(nil), Type: ptr91}
	ptr93 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr94 := system.String("object")
	ptr95 := &system.Type{Object: ptr92, Embed: []*system.Reference{ptr93}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr94, Rule: (*system.Type)(nil)}
	ptr96 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@sibling"}
	ptr97 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr98 := &system.Object{Description: "Automatically created basic rule for sibling", Id: ptr96, Rules: []system.RuleInterface(nil), Type: ptr97}
	ptr99 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr100 := system.String("object")
	ptr101 := &system.Type{Object: ptr98, Embed: []*system.Reference{ptr99}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr100, Rule: (*system.Type)(nil)}
	ptr102 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simple"}
	ptr103 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr104 := &system.Object{Description: "Automatically created basic rule for simple", Id: ptr102, Rules: []system.RuleInterface(nil), Type: ptr103}
	ptr105 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr106 := system.String("object")
	ptr107 := &system.Type{Object: ptr104, Embed: []*system.Reference{ptr105}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr106, Rule: (*system.Type)(nil)}
	ptr108 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simpleItem"}
	ptr109 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr110 := &system.Object{Description: "Automatically created basic rule for simpleItem", Id: ptr108, Rules: []system.RuleInterface(nil), Type: ptr109}
	ptr111 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr112 := system.String("object")
	ptr113 := &system.Type{Object: ptr110, Embed: []*system.Reference{ptr111}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr112, Rule: (*system.Type)(nil)}
	ptr114 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@typed"}
	ptr115 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr116 := &system.Object{Description: "Automatically created basic rule for typed", Id: ptr114, Rules: []system.RuleInterface(nil), Type: ptr115}
	ptr117 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr118 := system.String("object")
	ptr119 := &system.Type{Object: ptr116, Embed: []*system.Reference{ptr117}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr118, Rule: (*system.Type)(nil)}
	ptr120 := &system.Reference{Package: "kego.io/selectors/tests", Name: "basic"}
	ptr121 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr122 := &system.Object{Id: ptr120, Rules: []system.RuleInterface(nil), Type: ptr121}
	ptr123 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr124 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr123}
	ptr125 := &system.Rule{}
	ptr126 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr127 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr126}
	ptr128 := &system.Rule{}
	ptr129 := &system.StringRule{Object: ptr127, Rule: ptr128, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr130 := &system.ArrayRule{Object: ptr124, Rule: ptr125, Items: ptr129, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr131 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr132 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr131}
	ptr133 := &system.Rule{}
	ptr134 := &system.StringRule{Object: ptr132, Rule: ptr133, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr135 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr136 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr135}
	ptr137 := &system.Rule{}
	ptr138 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr139 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr138}
	ptr140 := &system.Rule{}
	ptr141 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr142 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr141}
	ptr143 := &system.Rule{}
	ptr144 := &system.StringRule{Object: ptr142, Rule: ptr143, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr145 := &system.MapRule{Object: ptr139, Rule: ptr140, Items: ptr144, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr146 := &system.ArrayRule{Object: ptr136, Rule: ptr137, Items: ptr145, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr147 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr148 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr147}
	ptr149 := &system.Rule{}
	ptr150 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr151 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr150}
	ptr152 := &system.Rule{}
	ptr153 := &system.StringRule{Object: ptr151, Rule: ptr152, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr154 := &system.MapRule{Object: ptr148, Rule: ptr149, Items: ptr153, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr155 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr156 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr155}
	ptr157 := &system.Rule{}
	ptr158 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr159 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr158}
	ptr160 := &system.Rule{}
	ptr161 := &system.StringRule{Object: ptr159, Rule: ptr160, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr162 := &system.ArrayRule{Object: ptr156, Rule: ptr157, Items: ptr161, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr163 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr164 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr163}
	ptr165 := &system.Rule{}
	ptr166 := &system.NumberRule{Object: ptr164, Rule: ptr165, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr167 := system.String("object")
	ptr168 := &system.Type{Object: ptr122, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"drinkPreference": ptr130, "favoriteColor": ptr134, "languagesSpoken": ptr146, "name": ptr154, "seatingPreference": ptr162, "weight": ptr166}, Is: []*system.Reference(nil), Native: &ptr167, Rule: (*system.Type)(nil)}
	ptr169 := &system.Reference{Package: "kego.io/selectors/tests", Name: "c"}
	ptr170 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr171 := &system.Object{Id: ptr169, Rules: []system.RuleInterface(nil), Type: ptr170}
	ptr172 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr173 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr172}
	ptr174 := &system.Rule{}
	ptr175 := &system.NumberRule{Object: ptr173, Rule: ptr174, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr176 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr177 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr176}
	ptr178 := &system.Rule{}
	ptr179 := &system.NumberRule{Object: ptr177, Rule: ptr178, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr180 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr181 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr180}
	ptr182 := &system.Rule{}
	ptr183 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr184 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr183}
	ptr185 := &system.Rule{}
	ptr186 := &system.NumberRule{Object: ptr184, Rule: ptr185, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr187 := &system.MapRule{Object: ptr181, Rule: ptr182, Items: ptr186, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr188 := system.String("object")
	ptr189 := &system.Type{Object: ptr171, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr175, "b": ptr179, "c": ptr187}, Is: []*system.Reference(nil), Native: &ptr188, Rule: (*system.Type)(nil)}
	ptr190 := &system.Reference{Package: "kego.io/selectors/tests", Name: "collision"}
	ptr191 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr192 := &system.Object{Id: ptr190, Rules: []system.RuleInterface(nil), Type: ptr191}
	ptr193 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr194 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr193}
	ptr195 := &system.Rule{}
	ptr196 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr197 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr196}
	ptr198 := &system.Rule{}
	ptr199 := &system.StringRule{Object: ptr197, Rule: ptr198, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr200 := &system.MapRule{Object: ptr194, Rule: ptr195, Items: ptr199, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr201 := system.String("object")
	ptr202 := &system.Type{Object: ptr192, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"number": ptr200}, Is: []*system.Reference(nil), Native: &ptr201, Rule: (*system.Type)(nil)}
	ptr203 := &system.Reference{Package: "kego.io/selectors/tests", Name: "diagram"}
	ptr204 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr205 := &system.Object{Id: ptr203, Rules: []system.RuleInterface(nil), Type: ptr204}
	ptr206 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr207 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr206}
	ptr208 := &system.Rule{}
	ptr209 := &system.StringRule{Object: ptr207, Rule: ptr208, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr210 := &system.Reference{Package: "kego.io/selectors/tests", Name: "image"}
	ptr211 := system.String("object")
	ptr212 := &system.Type{Object: ptr205, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"url": ptr209}, Is: []*system.Reference{ptr210}, Native: &ptr211, Rule: (*system.Type)(nil)}
	ptr213 := &system.Reference{Package: "kego.io/selectors/tests", Name: "expr"}
	ptr214 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr215 := &system.Object{Id: ptr213, Rules: []system.RuleInterface(nil), Type: ptr214}
	ptr216 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr217 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr216}
	ptr218 := &system.Rule{}
	ptr219 := &system.BoolRule{Object: ptr217, Rule: ptr218, Default: (*system.Bool)(nil)}
	ptr220 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr221 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr220}
	ptr222 := &system.Rule{}
	ptr223 := &system.NumberRule{Object: ptr221, Rule: ptr222, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr224 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr225 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr224}
	ptr226 := &system.Rule{}
	ptr227 := &system.NumberRule{Object: ptr225, Rule: ptr226, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr228 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr229 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr228}
	ptr230 := &system.Rule{}
	ptr231 := &system.StringRule{Object: ptr229, Rule: ptr230, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr232 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr233 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr232}
	ptr234 := &system.Rule{}
	ptr235 := &system.StringRule{Object: ptr233, Rule: ptr234, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr236 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr237 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr236}
	ptr238 := &system.Rule{}
	ptr239 := &system.StringRule{Object: ptr237, Rule: ptr238, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr240 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr241 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr240}
	ptr242 := &system.Rule{}
	ptr243 := &system.BoolRule{Object: ptr241, Rule: ptr242, Default: (*system.Bool)(nil)}
	ptr244 := system.String("object")
	ptr245 := &system.Type{Object: ptr215, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"false": ptr219, "float": ptr223, "int": ptr227, "null": ptr231, "string": ptr235, "string2": ptr239, "true": ptr243}, Is: []*system.Reference(nil), Native: &ptr244, Rule: (*system.Type)(nil)}
	ptr246 := &system.Reference{Package: "kego.io/selectors/tests", Name: "gallery"}
	ptr247 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr248 := &system.Object{Description: "This represents a gallery - it's just a list of images", Id: ptr246, Rules: []system.RuleInterface(nil), Type: ptr247}
	ptr249 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr250 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr249}
	ptr251 := &system.Rule{}
	ptr252 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr253 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr252}
	ptr254 := &system.Rule{}
	ptr255 := &tests.ImageRule{Object: ptr253, Rule: ptr254}
	ptr256 := &system.MapRule{Object: ptr250, Rule: ptr251, Items: ptr255, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr257 := system.String("object")
	ptr258 := &system.Type{Object: ptr248, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"images": ptr256}, Is: []*system.Reference(nil), Native: &ptr257, Rule: (*system.Type)(nil)}
	ptr259 := &system.Reference{Package: "kego.io/selectors/tests", Name: "image"}
	ptr260 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr261 := &system.Object{Id: ptr259, Rules: []system.RuleInterface(nil), Type: ptr260}
	ptr262 := system.String("object")
	ptr263 := &system.Type{Object: ptr261, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Interface: true, Is: []*system.Reference(nil), Native: &ptr262, Rule: (*system.Type)(nil)}
	ptr264 := &system.Reference{Package: "kego.io/selectors/tests", Name: "instance"}
	ptr265 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr266 := &system.Object{Id: ptr264, Rules: []system.RuleInterface(nil), Type: ptr265}
	ptr267 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr268 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr267}
	ptr269 := &system.Rule{}
	ptr270 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr271 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr270}
	ptr272 := &system.Rule{}
	ptr273 := &tests.InstanceItemRule{Object: ptr271, Rule: ptr272}
	ptr274 := &system.MapRule{Object: ptr268, Rule: ptr269, Items: ptr273, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr275 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr276 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr275}
	ptr277 := &system.Rule{}
	ptr278 := &system.StringRule{Object: ptr276, Rule: ptr277, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr279 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr280 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr279}
	ptr281 := &system.Rule{}
	ptr282 := &system.StringRule{Object: ptr280, Rule: ptr281, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr283 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr284 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr283}
	ptr285 := &system.Rule{}
	ptr286 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr287 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr286}
	ptr288 := &system.Rule{}
	ptr289 := &tests.RightscaleLinkRule{Object: ptr287, Rule: ptr288}
	ptr290 := &system.ArrayRule{Object: ptr284, Rule: ptr285, Items: ptr289, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr291 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr292 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr291}
	ptr293 := &system.Rule{}
	ptr294 := &system.StringRule{Object: ptr292, Rule: ptr293, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr295 := system.String("object")
	ptr296 := &system.Type{Object: ptr266, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"child": ptr274, "cloud_type": ptr278, "display_name": ptr282, "links": ptr290, "name": ptr294}, Is: []*system.Reference(nil), Native: &ptr295, Rule: (*system.Type)(nil)}
	ptr297 := &system.Reference{Package: "kego.io/selectors/tests", Name: "instanceItem"}
	ptr298 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr299 := &system.Object{Id: ptr297, Rules: []system.RuleInterface(nil), Type: ptr298}
	ptr300 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr301 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr300}
	ptr302 := &system.Rule{}
	ptr303 := &system.StringRule{Object: ptr301, Rule: ptr302, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr304 := system.String("object")
	ptr305 := &system.Type{Object: ptr299, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"name": ptr303}, Is: []*system.Reference(nil), Native: &ptr304, Rule: (*system.Type)(nil)}
	ptr306 := &system.Reference{Package: "kego.io/selectors/tests", Name: "kid"}
	ptr307 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr308 := &system.Object{Id: ptr306, Rules: []system.RuleInterface(nil), Type: ptr307}
	ptr309 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr310 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr309}
	ptr311 := &system.Rule{}
	ptr312 := &system.StringRule{Object: ptr310, Rule: ptr311, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr313 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr314 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr313}
	ptr315 := &system.Rule{}
	ptr316 := &system.StringRule{Object: ptr314, Rule: ptr315, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr317 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr318 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr317}
	ptr319 := &system.Rule{Optional: true}
	ptr320 := &system.BoolRule{Object: ptr318, Rule: ptr319, Default: (*system.Bool)(nil)}
	ptr321 := system.String("object")
	ptr322 := &system.Type{Object: ptr308, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"language": ptr312, "level": ptr316, "preferred": ptr320}, Is: []*system.Reference(nil), Native: &ptr321, Rule: (*system.Type)(nil)}
	ptr323 := &system.Reference{Package: "kego.io/selectors/tests", Name: "photo"}
	ptr324 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr325 := &system.Object{Description: "This represents an image, and contains path, server and protocol separately", Id: ptr323, Rules: []system.RuleInterface(nil), Type: ptr324}
	ptr326 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr327 := &system.Object{Description: "The path for the url - e.g. /foo/bar.jpg", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr326}
	ptr328 := &system.Rule{}
	ptr329 := &system.StringRule{Object: ptr327, Rule: ptr328, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr330 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr331 := &system.Object{Description: "The protocol for the url - e.g. http or https", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr330}
	ptr332 := &system.Rule{Optional: true}
	ptr333 := system.String("http")
	ptr334 := &system.StringRule{Object: ptr331, Rule: ptr332, Default: &ptr333, Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr335 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr336 := &system.Object{Description: "The server for the url - e.g. www.google.com", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr335}
	ptr337 := &system.Rule{}
	ptr338 := &system.StringRule{Object: ptr336, Rule: ptr337, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr339 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rectangle"}
	ptr340 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr339}
	ptr341 := &system.Rule{Optional: true}
	ptr342 := &tests.RectangleRule{Object: ptr340, Rule: ptr341}
	ptr343 := &system.Reference{Package: "kego.io/selectors/tests", Name: "image"}
	ptr344 := system.String("object")
	ptr345 := &system.Type{Object: ptr325, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"path": ptr329, "protocol": ptr334, "server": ptr338, "size": ptr342}, Is: []*system.Reference{ptr343}, Native: &ptr344, Rule: (*system.Type)(nil)}
	ptr346 := &system.Reference{Package: "kego.io/selectors/tests", Name: "polykids"}
	ptr347 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr348 := &system.Object{Id: ptr346, Rules: []system.RuleInterface(nil), Type: ptr347}
	ptr349 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr350 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr349}
	ptr351 := &system.Rule{}
	ptr352 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr353 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr352}
	ptr354 := &system.Rule{}
	ptr355 := &tests.KidRule{Object: ptr353, Rule: ptr354}
	ptr356 := &system.ArrayRule{Object: ptr350, Rule: ptr351, Items: ptr355, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr357 := system.String("object")
	ptr358 := &system.Type{Object: ptr348, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr356}, Is: []*system.Reference(nil), Native: &ptr357, Rule: (*system.Type)(nil)}
	ptr359 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rectangle"}
	ptr360 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr361 := &system.Object{Id: ptr359, Rules: []system.RuleInterface(nil), Type: ptr360}
	ptr362 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr363 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr362}
	ptr364 := &system.Rule{}
	ptr365 := &system.IntRule{Object: ptr363, Rule: ptr364, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr366 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr367 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr366}
	ptr368 := &system.Rule{}
	ptr369 := &system.IntRule{Object: ptr367, Rule: ptr368, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr370 := system.String("object")
	ptr371 := &system.Type{Object: ptr361, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"height": ptr365, "width": ptr369}, Is: []*system.Reference(nil), Native: &ptr370, Rule: (*system.Type)(nil)}
	ptr372 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscale"}
	ptr373 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr374 := &system.Object{Id: ptr372, Rules: []system.RuleInterface(nil), Type: ptr373}
	ptr375 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr376 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr375}
	ptr377 := &system.Rule{}
	ptr378 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@instanceItem"}
	ptr379 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr378}
	ptr380 := &system.Rule{}
	ptr381 := &tests.InstanceItemRule{Object: ptr379, Rule: ptr380}
	ptr382 := &system.MapRule{Object: ptr376, Rule: ptr377, Items: ptr381, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr383 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr384 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr383}
	ptr385 := &system.Rule{}
	ptr386 := &system.StringRule{Object: ptr384, Rule: ptr385, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr387 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr388 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr387}
	ptr389 := &system.Rule{}
	ptr390 := &system.StringRule{Object: ptr388, Rule: ptr389, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr391 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr392 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr391}
	ptr393 := &system.Rule{}
	ptr394 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscaleLink"}
	ptr395 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr394}
	ptr396 := &system.Rule{}
	ptr397 := &tests.RightscaleLinkRule{Object: ptr395, Rule: ptr396}
	ptr398 := &system.ArrayRule{Object: ptr392, Rule: ptr393, Items: ptr397, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr399 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr400 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr399}
	ptr401 := &system.Rule{}
	ptr402 := &system.StringRule{Object: ptr400, Rule: ptr401, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr403 := system.String("object")
	ptr404 := &system.Type{Object: ptr374, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"child": ptr382, "cloud_type": ptr386, "display_name": ptr390, "links": ptr398, "name": ptr402}, Is: []*system.Reference(nil), Native: &ptr403, Rule: (*system.Type)(nil)}
	ptr405 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscaleLink"}
	ptr406 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr407 := &system.Object{Id: ptr405, Rules: []system.RuleInterface(nil), Type: ptr406}
	ptr408 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr409 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr408}
	ptr410 := &system.Rule{}
	ptr411 := &system.StringRule{Object: ptr409, Rule: ptr410, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr412 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr413 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr412}
	ptr414 := &system.Rule{}
	ptr415 := &system.StringRule{Object: ptr413, Rule: ptr414, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr416 := system.String("object")
	ptr417 := &system.Type{Object: ptr407, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"href": ptr411, "rel": ptr415}, Is: []*system.Reference(nil), Native: &ptr416, Rule: (*system.Type)(nil)}
	ptr418 := &system.Reference{Package: "kego.io/selectors/tests", Name: "rightscaleList"}
	ptr419 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr420 := &system.Object{Id: ptr418, Rules: []system.RuleInterface(nil), Type: ptr419}
	ptr421 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr422 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr421}
	ptr423 := &system.Rule{}
	ptr424 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@rightscale"}
	ptr425 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr424}
	ptr426 := &system.Rule{}
	ptr427 := &tests.RightscaleRule{Object: ptr425, Rule: ptr426}
	ptr428 := &system.ArrayRule{Object: ptr422, Rule: ptr423, Items: ptr427, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr429 := system.String("object")
	ptr430 := &system.Type{Object: ptr420, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"foo": ptr428}, Is: []*system.Reference(nil), Native: &ptr429, Rule: (*system.Type)(nil)}
	ptr431 := &system.Reference{Package: "kego.io/selectors/tests", Name: "sibling"}
	ptr432 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr433 := &system.Object{Id: ptr431, Rules: []system.RuleInterface(nil), Type: ptr432}
	ptr434 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr435 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr434}
	ptr436 := &system.Rule{}
	ptr437 := &system.NumberRule{Object: ptr435, Rule: ptr436, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr438 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr439 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr438}
	ptr440 := &system.Rule{}
	ptr441 := &system.NumberRule{Object: ptr439, Rule: ptr440, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr442 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@c"}
	ptr443 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr442}
	ptr444 := &system.Rule{}
	ptr445 := &tests.CRule{Object: ptr443, Rule: ptr444}
	ptr446 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr447 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr446}
	ptr448 := &system.Rule{}
	ptr449 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr450 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr449}
	ptr451 := &system.Rule{}
	ptr452 := &system.NumberRule{Object: ptr450, Rule: ptr451, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr453 := &system.MapRule{Object: ptr447, Rule: ptr448, Items: ptr452, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr454 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr455 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr454}
	ptr456 := &system.Rule{}
	ptr457 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr458 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr457}
	ptr459 := &system.Rule{}
	ptr460 := &system.NumberRule{Object: ptr458, Rule: ptr459, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr461 := &system.MapRule{Object: ptr455, Rule: ptr456, Items: ptr460, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr462 := system.String("object")
	ptr463 := &system.Type{Object: ptr433, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr437, "b": ptr441, "c": ptr445, "d": ptr453, "e": ptr461}, Is: []*system.Reference(nil), Native: &ptr462, Rule: (*system.Type)(nil)}
	ptr464 := &system.Reference{Package: "kego.io/selectors/tests", Name: "simple"}
	ptr465 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr466 := &system.Object{Id: ptr464, Rules: []system.RuleInterface(nil), Type: ptr465}
	ptr467 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@simpleItem"}
	ptr468 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr467}
	ptr469 := &system.Rule{}
	ptr470 := &tests.SimpleItemRule{Object: ptr468, Rule: ptr469}
	ptr471 := system.String("object")
	ptr472 := &system.Type{Object: ptr466, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"a": ptr470}, Is: []*system.Reference(nil), Native: &ptr471, Rule: (*system.Type)(nil)}
	ptr473 := &system.Reference{Package: "kego.io/selectors/tests", Name: "simpleItem"}
	ptr474 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr475 := &system.Object{Id: ptr473, Rules: []system.RuleInterface(nil), Type: ptr474}
	ptr476 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr477 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr476}
	ptr478 := &system.Rule{}
	ptr479 := &system.StringRule{Object: ptr477, Rule: ptr478, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr480 := system.String("object")
	ptr481 := &system.Type{Object: ptr475, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"b": ptr479}, Is: []*system.Reference(nil), Native: &ptr480, Rule: (*system.Type)(nil)}
	ptr482 := &system.Reference{Package: "kego.io/selectors/tests", Name: "typed"}
	ptr483 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr484 := &system.Object{Id: ptr482, Rules: []system.RuleInterface(nil), Type: ptr483}
	ptr485 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@image"}
	ptr486 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr485}
	ptr487 := &system.Rule{}
	ptr488 := &tests.ImageRule{Object: ptr486, Rule: ptr487}
	ptr489 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr490 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr489}
	ptr491 := &system.Rule{}
	ptr492 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr493 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr492}
	ptr494 := &system.Rule{}
	ptr495 := &system.StringRule{Object: ptr493, Rule: ptr494, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr496 := &system.ArrayRule{Object: ptr490, Rule: ptr491, Items: ptr495, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr497 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr498 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr497}
	ptr499 := &system.Rule{}
	ptr500 := &system.StringRule{Object: ptr498, Rule: ptr499, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr501 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr502 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr501}
	ptr503 := &system.Rule{}
	ptr504 := &system.Reference{Package: "kego.io/selectors/tests", Name: "@kid"}
	ptr505 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr504}
	ptr506 := &system.Rule{}
	ptr507 := &tests.KidRule{Object: ptr505, Rule: ptr506}
	ptr508 := &system.MapRule{Object: ptr502, Rule: ptr503, Items: ptr507, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr509 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr510 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr509}
	ptr511 := &system.Rule{}
	ptr512 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr513 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr512}
	ptr514 := &system.Rule{}
	ptr515 := &system.StringRule{Object: ptr513, Rule: ptr514, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr516 := &system.MapRule{Object: ptr510, Rule: ptr511, Items: ptr515, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr517 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr518 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr517}
	ptr519 := &system.Rule{}
	ptr520 := &system.NumberRule{Object: ptr518, Rule: ptr519, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr521 := system.String("object")
	ptr522 := &system.Type{Object: ptr484, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"avatar": ptr488, "drinkPreference": ptr496, "favoriteColor": ptr500, "kids": ptr508, "name": ptr516, "weight": ptr520}, Is: []*system.Reference(nil), Native: &ptr521, Rule: (*system.Type)(nil)}
	system.Register("kego.io/selectors/tests", "@basic", ptr5, 0xe2f725e9d48b69d4)
	system.Register("kego.io/selectors/tests", "@c", ptr11, 0x6a4bf0b03046c68a)
	system.Register("kego.io/selectors/tests", "@collision", ptr17, 0x2f6382cf84b27ee7)
	system.Register("kego.io/selectors/tests", "@diagram", ptr23, 0x2076b0eaf334855b)
	system.Register("kego.io/selectors/tests", "@expr", ptr29, 0x6214e678b1df35e3)
	system.Register("kego.io/selectors/tests", "@gallery", ptr35, 0xa2261dbb985b3d3)
	system.Register("kego.io/selectors/tests", "@image", ptr41, 0x2a2a6f416ac31013)
	system.Register("kego.io/selectors/tests", "@instance", ptr47, 0xa7637e9d5bf458e9)
	system.Register("kego.io/selectors/tests", "@instanceItem", ptr53, 0x2dca71ec3918c621)
	system.Register("kego.io/selectors/tests", "@kid", ptr59, 0x3b576fd38b04a2eb)
	system.Register("kego.io/selectors/tests", "@photo", ptr65, 0x6c010530199ae92f)
	system.Register("kego.io/selectors/tests", "@polykids", ptr71, 0xebaffecb552df4d1)
	system.Register("kego.io/selectors/tests", "@rectangle", ptr77, 0x21539507256190ab)
	system.Register("kego.io/selectors/tests", "@rightscale", ptr83, 0xde456fd6916c6f51)
	system.Register("kego.io/selectors/tests", "@rightscaleLink", ptr89, 0x127d9489c45697ea)
	system.Register("kego.io/selectors/tests", "@rightscaleList", ptr95, 0x6a9527067852e20b)
	system.Register("kego.io/selectors/tests", "@sibling", ptr101, 0xac837d672ff74ed6)
	system.Register("kego.io/selectors/tests", "@simple", ptr107, 0x7054dc6469f4db46)
	system.Register("kego.io/selectors/tests", "@simpleItem", ptr113, 0xac167d73687ccb1f)
	system.Register("kego.io/selectors/tests", "@typed", ptr119, 0x216d0e1d4c22bb2d)
	system.Register("kego.io/selectors/tests", "basic", ptr168, 0xe2f725e9d48b69d4)
	system.Register("kego.io/selectors/tests", "c", ptr189, 0x6a4bf0b03046c68a)
	system.Register("kego.io/selectors/tests", "collision", ptr202, 0x2f6382cf84b27ee7)
	system.Register("kego.io/selectors/tests", "diagram", ptr212, 0x2076b0eaf334855b)
	system.Register("kego.io/selectors/tests", "expr", ptr245, 0x6214e678b1df35e3)
	system.Register("kego.io/selectors/tests", "gallery", ptr258, 0xa2261dbb985b3d3)
	system.Register("kego.io/selectors/tests", "image", ptr263, 0x2a2a6f416ac31013)
	system.Register("kego.io/selectors/tests", "instance", ptr296, 0xa7637e9d5bf458e9)
	system.Register("kego.io/selectors/tests", "instanceItem", ptr305, 0x2dca71ec3918c621)
	system.Register("kego.io/selectors/tests", "kid", ptr322, 0x3b576fd38b04a2eb)
	system.Register("kego.io/selectors/tests", "photo", ptr345, 0x6c010530199ae92f)
	system.Register("kego.io/selectors/tests", "polykids", ptr358, 0xebaffecb552df4d1)
	system.Register("kego.io/selectors/tests", "rectangle", ptr371, 0x21539507256190ab)
	system.Register("kego.io/selectors/tests", "rightscale", ptr404, 0xde456fd6916c6f51)
	system.Register("kego.io/selectors/tests", "rightscaleLink", ptr417, 0x127d9489c45697ea)
	system.Register("kego.io/selectors/tests", "rightscaleList", ptr430, 0x6a9527067852e20b)
	system.Register("kego.io/selectors/tests", "sibling", ptr463, 0xac837d672ff74ed6)
	system.Register("kego.io/selectors/tests", "simple", ptr472, 0x7054dc6469f4db46)
	system.Register("kego.io/selectors/tests", "simpleItem", ptr481, 0xac167d73687ccb1f)
	system.Register("kego.io/selectors/tests", "typed", ptr522, 0x216d0e1d4c22bb2d)
}
