package types

import (
	"kego.io/system"
)

func init() {
	ptr0 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr1 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr2 := &system.Object{Description: "Restriction rules for arrays", Id: ptr0, Rules: []system.RuleInterface(nil), Type: ptr1}
	ptr3 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr4 := &system.Reference{Package: "kego.io/system", Name: "@rule"}
	ptr5 := &system.Object{Description: "This is a rule object, defining the type and restrictions on the value of the items", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr4}
	ptr6 := &system.Rule{Interface: true}
	ptr7 := &system.RuleRule{Object: ptr5, Rule: ptr6}
	ptr8 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr9 := &system.Object{Description: "This is the maximum number of items allowed in the array", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr8}
	ptr10 := &system.Rule{Optional: true}
	ptr11 := system.Int(0)
	ptr12 := &system.IntRule{Object: ptr9, Rule: ptr10, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: &ptr11, MultipleOf: (*system.Int)(nil)}
	ptr13 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr14 := &system.Object{Description: "This is the minimum number of items allowed in the array", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr13}
	ptr15 := &system.Rule{Optional: true}
	ptr16 := system.Int(0)
	ptr17 := &system.IntRule{Object: ptr14, Rule: ptr15, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: &ptr16, MultipleOf: (*system.Int)(nil)}
	ptr18 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr19 := &system.Object{Description: "If this is true, each item must be unique", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr18}
	ptr20 := &system.Rule{Optional: true}
	ptr21 := &system.JsonBoolRule{Object: ptr19, Rule: ptr20}
	ptr22 := system.String("object")
	ptr23 := &system.Type{Object: ptr2, Embed: []*system.Reference{ptr3}, Fields: map[string]system.RuleInterface{"items": ptr7, "maxItems": ptr12, "minItems": ptr17, "uniqueItems": ptr21}, Is: []*system.Reference(nil), Native: &ptr22, Rule: (*system.Type)(nil)}
	ptr24 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr25 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr26 := &system.Object{Description: "Restriction rules for bools", Id: ptr24, Rules: []system.RuleInterface(nil), Type: ptr25}
	ptr27 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr28 := &system.Reference{Package: "kego.io/system", Name: "@bool"}
	ptr29 := &system.Object{Description: "Default value if this is missing or null", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr28}
	ptr30 := &system.Rule{Optional: true}
	ptr31 := &system.BoolRule{Object: ptr29, Rule: ptr30, Default: (*system.Bool)(nil)}
	ptr32 := system.String("object")
	ptr33 := &system.Type{Object: ptr26, Embed: []*system.Reference{ptr27}, Fields: map[string]system.RuleInterface{"default": ptr31}, Is: []*system.Reference(nil), Native: &ptr32, Rule: (*system.Type)(nil)}
	ptr34 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr35 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr36 := &system.Object{Description: "Restriction rules for integers", Id: ptr34, Rules: []system.RuleInterface(nil), Type: ptr35}
	ptr37 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr38 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr39 := &system.Object{Description: "Default value if this property is omitted", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr38}
	ptr40 := &system.Rule{Optional: true}
	ptr41 := &system.IntRule{Object: ptr39, Rule: ptr40, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr42 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr43 := &system.Object{Description: "This provides an upper bound for the restriction", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr42}
	ptr44 := &system.Rule{Optional: true}
	ptr45 := &system.IntRule{Object: ptr43, Rule: ptr44, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr46 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr47 := &system.Object{Description: "This provides a lower bound for the restriction", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr46}
	ptr48 := &system.Rule{Optional: true}
	ptr49 := &system.IntRule{Object: ptr47, Rule: ptr48, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr50 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr51 := &system.Object{Description: "This restricts the number to be a multiple of the given number", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr50}
	ptr52 := &system.Rule{Optional: true}
	ptr53 := &system.IntRule{Object: ptr51, Rule: ptr52, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr54 := system.String("object")
	ptr55 := &system.Type{Object: ptr36, Embed: []*system.Reference{ptr37}, Fields: map[string]system.RuleInterface{"default": ptr41, "maximum": ptr45, "minimum": ptr49, "multipleOf": ptr53}, Is: []*system.Reference(nil), Native: &ptr54, Rule: (*system.Type)(nil)}
	ptr56 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr57 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr58 := &system.Object{Description: "Restriction rules for maps", Id: ptr56, Rules: []system.RuleInterface(nil), Type: ptr57}
	ptr59 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr60 := &system.Reference{Package: "kego.io/system", Name: "@rule"}
	ptr61 := &system.Object{Description: "This is a rule object, defining the type and restrictions on the value of the items.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr60}
	ptr62 := &system.Rule{Interface: true}
	ptr63 := &system.RuleRule{Object: ptr61, Rule: ptr62}
	ptr64 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr65 := &system.Object{Description: "This is the maximum number of items alowed in the array", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr64}
	ptr66 := &system.Rule{Optional: true}
	ptr67 := system.Int(0)
	ptr68 := &system.IntRule{Object: ptr65, Rule: ptr66, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: &ptr67, MultipleOf: (*system.Int)(nil)}
	ptr69 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr70 := &system.Object{Description: "This is the minimum number of items alowed in the array", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr69}
	ptr71 := &system.Rule{Optional: true}
	ptr72 := system.Int(0)
	ptr73 := &system.IntRule{Object: ptr70, Rule: ptr71, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: &ptr72, MultipleOf: (*system.Int)(nil)}
	ptr74 := system.String("object")
	ptr75 := &system.Type{Object: ptr58, Embed: []*system.Reference{ptr59}, Fields: map[string]system.RuleInterface{"items": ptr63, "maxItems": ptr68, "minItems": ptr73}, Is: []*system.Reference(nil), Native: &ptr74, Rule: (*system.Type)(nil)}
	ptr76 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr77 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr78 := &system.Object{Description: "Restriction rules for numbers", Id: ptr76, Rules: []system.RuleInterface(nil), Type: ptr77}
	ptr79 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr80 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr81 := &system.Object{Description: "Default value if this property is omitted", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr80}
	ptr82 := &system.Rule{Optional: true}
	ptr83 := &system.NumberRule{Object: ptr81, Rule: ptr82, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr84 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr85 := &system.Object{Description: "If this is true, the value must be less than maximum. If false or not provided, the value must be less than or equal to the maximum.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr84}
	ptr86 := &system.Rule{Optional: true}
	ptr87 := &system.JsonBoolRule{Object: ptr85, Rule: ptr86}
	ptr88 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr89 := &system.Object{Description: "If this is true, the value must be greater than minimum. If false or not provided, the value must be greater than or equal to the minimum.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr88}
	ptr90 := &system.Rule{Optional: true}
	ptr91 := &system.JsonBoolRule{Object: ptr89, Rule: ptr90}
	ptr92 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr93 := &system.Object{Description: "This provides an upper bound for the restriction", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr92}
	ptr94 := &system.Rule{Optional: true}
	ptr95 := &system.NumberRule{Object: ptr93, Rule: ptr94, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr96 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr97 := &system.Object{Description: "This provides a lower bound for the restriction", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr96}
	ptr98 := &system.Rule{Optional: true}
	ptr99 := &system.NumberRule{Object: ptr97, Rule: ptr98, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr100 := &system.Reference{Package: "kego.io/system", Name: "@number"}
	ptr101 := &system.Object{Description: "This restricts the number to be a multiple of the given number", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr100}
	ptr102 := &system.Rule{Optional: true}
	ptr103 := &system.NumberRule{Object: ptr101, Rule: ptr102, Default: (*system.Number)(nil), Maximum: (*system.Number)(nil), Minimum: (*system.Number)(nil), MultipleOf: (*system.Number)(nil)}
	ptr104 := system.String("object")
	ptr105 := &system.Type{Object: ptr78, Embed: []*system.Reference{ptr79}, Fields: map[string]system.RuleInterface{"default": ptr83, "exclusiveMaximum": ptr87, "exclusiveMinimum": ptr91, "maximum": ptr95, "minimum": ptr99, "multipleOf": ptr103}, Is: []*system.Reference(nil), Native: &ptr104, Rule: (*system.Type)(nil)}
	ptr106 := &system.Reference{Package: "kego.io/system", Name: "@object"}
	ptr107 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr108 := &system.Object{Description: "Automatically created basic rule for object", Id: ptr106, Rules: []system.RuleInterface(nil), Type: ptr107}
	ptr109 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr110 := system.String("object")
	ptr111 := &system.Type{Object: ptr108, Embed: []*system.Reference{ptr109}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr110, Rule: (*system.Type)(nil)}
	ptr112 := &system.Reference{Package: "kego.io/system", Name: "@package"}
	ptr113 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr114 := &system.Object{Description: "Automatically created basic rule for package", Id: ptr112, Rules: []system.RuleInterface(nil), Type: ptr113}
	ptr115 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr116 := system.String("object")
	ptr117 := &system.Type{Object: ptr114, Embed: []*system.Reference{ptr115}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr116, Rule: (*system.Type)(nil)}
	ptr118 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr119 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr120 := &system.Object{Description: "Restriction rules for references", Id: ptr118, Rules: []system.RuleInterface(nil), Type: ptr119}
	ptr121 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr122 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr123 := &system.Object{Description: "Default value of this is missing or null", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr122}
	ptr124 := &system.Rule{Optional: true}
	ptr125 := &system.ReferenceRule{Object: ptr123, Rule: ptr124, Default: (*system.Reference)(nil)}
	ptr126 := system.String("object")
	ptr127 := &system.Type{Object: ptr120, Embed: []*system.Reference{ptr121}, Fields: map[string]system.RuleInterface{"default": ptr125}, Is: []*system.Reference(nil), Native: &ptr126, Rule: (*system.Type)(nil)}
	ptr128 := &system.Reference{Package: "kego.io/system", Name: "@rule"}
	ptr129 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr130 := &system.Object{Description: "Automatically created basic rule for rule", Id: ptr128, Rules: []system.RuleInterface(nil), Type: ptr129}
	ptr131 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr132 := system.String("object")
	ptr133 := &system.Type{Object: ptr130, Embed: []*system.Reference{ptr131}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr132, Rule: (*system.Type)(nil)}
	ptr134 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr135 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr136 := &system.Object{Description: "Restriction rules for strings", Id: ptr134, Rules: []system.RuleInterface(nil), Type: ptr135}
	ptr137 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr138 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr139 := &system.Object{Description: "Default value of this is missing or null", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr138}
	ptr140 := &system.Rule{Optional: true}
	ptr141 := &system.StringRule{Object: ptr139, Rule: ptr140, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr142 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr143 := &system.Object{Description: "The value of this string is restricted to one of the provided values", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr142}
	ptr144 := &system.Rule{Optional: true}
	ptr145 := &system.Reference{Package: "kego.io/json", Name: "@string"}
	ptr146 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr145}
	ptr147 := &system.Rule{}
	ptr148 := &system.JsonStringRule{Object: ptr146, Rule: ptr147}
	ptr149 := &system.ArrayRule{Object: ptr143, Rule: ptr144, Items: ptr148, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr150 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr151 := &system.Object{Description: "This is a string that the value must match", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr150}
	ptr152 := &system.Rule{Optional: true}
	ptr153 := &system.StringRule{Object: ptr151, Rule: ptr152, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr154 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr155 := &system.Object{Description: "This restricts the value to one of several built-in formats", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr154}
	ptr156 := &system.Rule{Optional: true}
	ptr157 := &system.StringRule{Object: ptr155, Rule: ptr156, Default: (*system.String)(nil), Enum: []string{"date-time", "email", "hostname", "ipv4", "ipv6", "uri"}, Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr158 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr159 := &system.Object{Description: "The value must be shorter or equal to the provided maximum length", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr158}
	ptr160 := &system.Rule{Optional: true}
	ptr161 := &system.IntRule{Object: ptr159, Rule: ptr160, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr162 := &system.Reference{Package: "kego.io/system", Name: "@int"}
	ptr163 := &system.Object{Description: "The value must be longer or equal to the provided minimum length", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr162}
	ptr164 := &system.Rule{Optional: true}
	ptr165 := &system.IntRule{Object: ptr163, Rule: ptr164, Default: (*system.Int)(nil), Maximum: (*system.Int)(nil), Minimum: (*system.Int)(nil), MultipleOf: (*system.Int)(nil)}
	ptr166 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr167 := &system.Object{Description: "This is a regex to match the value to", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr166}
	ptr168 := &system.Rule{Optional: true}
	ptr169 := &system.StringRule{Object: ptr167, Rule: ptr168, Default: (*system.String)(nil), Enum: []string(nil), Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr170 := system.String("object")
	ptr171 := &system.Type{Object: ptr136, Embed: []*system.Reference{ptr137}, Fields: map[string]system.RuleInterface{"default": ptr141, "enum": ptr149, "equal": ptr153, "format": ptr157, "maxLength": ptr161, "minLength": ptr165, "pattern": ptr169}, Is: []*system.Reference(nil), Native: &ptr170, Rule: (*system.Type)(nil)}
	ptr172 := &system.Reference{Package: "kego.io/system", Name: "@type"}
	ptr173 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr174 := &system.Object{Description: "Automatically created basic rule for type", Id: ptr172, Rules: []system.RuleInterface(nil), Type: ptr173}
	ptr175 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr176 := system.String("object")
	ptr177 := &system.Type{Object: ptr174, Embed: []*system.Reference{ptr175}, Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr176, Rule: (*system.Type)(nil)}
	ptr178 := &system.Reference{Package: "kego.io/system", Name: "array"}
	ptr179 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr180 := &system.Object{Description: "This is the native json array data type", Id: ptr178, Rules: []system.RuleInterface(nil), Type: ptr179}
	ptr181 := system.String("array")
	ptr182 := &system.Type{Object: ptr180, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr181, Rule: ptr23}
	ptr183 := &system.Reference{Package: "kego.io/system", Name: "bool"}
	ptr184 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr185 := &system.Object{Description: "This is the native json bool data type", Id: ptr183, Rules: []system.RuleInterface(nil), Type: ptr184}
	ptr186 := system.String("bool")
	ptr187 := &system.Type{Object: ptr185, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr186, Rule: ptr33}
	ptr188 := &system.Reference{Package: "kego.io/system", Name: "int"}
	ptr189 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr190 := &system.Object{Description: "This is the int data type", Id: ptr188, Rules: []system.RuleInterface(nil), Type: ptr189}
	ptr191 := system.String("number")
	ptr192 := &system.Type{Object: ptr190, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr191, Rule: ptr55}
	ptr193 := &system.Reference{Package: "kego.io/system", Name: "map"}
	ptr194 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr195 := &system.Object{Description: "This is the native json object data type.", Id: ptr193, Rules: []system.RuleInterface(nil), Type: ptr194}
	ptr196 := system.String("map")
	ptr197 := &system.Type{Object: ptr195, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr196, Rule: ptr75}
	ptr198 := &system.Reference{Package: "kego.io/system", Name: "number"}
	ptr199 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr200 := &system.Object{Description: "This is the native json number data type", Id: ptr198, Rules: []system.RuleInterface(nil), Type: ptr199}
	ptr201 := system.String("number")
	ptr202 := &system.Type{Object: ptr200, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr201, Rule: ptr105}
	ptr203 := &system.Reference{Package: "kego.io/system", Name: "object"}
	ptr204 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr205 := &system.Object{Description: "This is the base type for the object interface. All ke objects have this type embedded.", Id: ptr203, Rules: []system.RuleInterface(nil), Type: ptr204}
	ptr206 := &system.Reference{Package: "kego.io/json", Name: "@string"}
	ptr207 := &system.Object{Description: "Description for the developer", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr206}
	ptr208 := &system.Rule{Optional: true}
	ptr209 := &system.JsonStringRule{Object: ptr207, Rule: ptr208}
	ptr210 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr211 := &system.Object{Description: "All global objects should have an id.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr210}
	ptr212 := &system.Rule{Optional: true}
	ptr213 := &system.ReferenceRule{Object: ptr211, Rule: ptr212, Default: (*system.Reference)(nil)}
	ptr214 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr215 := &system.Object{Description: "Extra validation rules for this object or descendants", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr214}
	ptr216 := &system.Rule{Optional: true}
	ptr217 := &system.Reference{Package: "kego.io/system", Name: "@rule"}
	ptr218 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr217}
	ptr219 := &system.Rule{Interface: true}
	ptr220 := &system.RuleRule{Object: ptr218, Rule: ptr219}
	ptr221 := &system.ArrayRule{Object: ptr215, Rule: ptr216, Items: ptr220, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr222 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr223 := &system.Object{Description: "Type of the object.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr222}
	ptr224 := &system.Rule{}
	ptr225 := &system.ReferenceRule{Object: ptr223, Rule: ptr224, Default: (*system.Reference)(nil)}
	ptr226 := system.String("object")
	ptr227 := &system.Type{Object: ptr205, Basic: true, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"description": ptr209, "id": ptr213, "rules": ptr221, "type": ptr225}, Is: []*system.Reference(nil), Native: &ptr226, Rule: (*system.Type)(nil)}
	ptr228 := &system.Reference{Package: "kego.io/system", Name: "package"}
	ptr229 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr230 := &system.Object{Description: "Package info - forms the root node of the package", Id: ptr228, Rules: []system.RuleInterface(nil), Type: ptr229}
	ptr231 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr232 := &system.Object{Description: "Map of import aliases used in this package: key = package path, value = alias.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr231}
	ptr233 := &system.Rule{Optional: true}
	ptr234 := &system.Reference{Package: "kego.io/json", Name: "@string"}
	ptr235 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr234}
	ptr236 := &system.Rule{}
	ptr237 := &system.JsonStringRule{Object: ptr235, Rule: ptr236}
	ptr238 := &system.MapRule{Object: ptr232, Rule: ptr233, Items: ptr237, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr239 := system.String("object")
	ptr240 := &system.Type{Object: ptr230, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"aliases": ptr238}, Is: []*system.Reference(nil), Native: &ptr239, Rule: (*system.Type)(nil)}
	ptr241 := &system.Reference{Package: "kego.io/system", Name: "reference"}
	ptr242 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr243 := &system.Object{Description: "This is a reference to another object, of the form: [local id] or [alias]:[id]", Id: ptr241, Rules: []system.RuleInterface(nil), Type: ptr242}
	ptr244 := system.String("string")
	ptr245 := &system.Type{Object: ptr243, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr244, Rule: ptr127}
	ptr246 := &system.Reference{Package: "kego.io/system", Name: "rule"}
	ptr247 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr248 := &system.Object{Description: "All rules will have this embedded in them.", Id: ptr246, Rules: []system.RuleInterface(nil), Type: ptr247}
	ptr249 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr250 := &system.Object{Description: "Special field that should be excluded when marshaling - e.g. package.global", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr249}
	ptr251 := &system.Rule{Optional: true}
	ptr252 := &system.JsonBoolRule{Object: ptr250, Rule: ptr251}
	ptr253 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr254 := &system.Object{Description: "Use the single method getter interface for this type", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr253}
	ptr255 := &system.Rule{Optional: true}
	ptr256 := &system.JsonBoolRule{Object: ptr254, Rule: ptr255}
	ptr257 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr258 := &system.Object{Description: "If this rule is a field, this specifies that the field is optional", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr257}
	ptr259 := &system.Rule{Optional: true}
	ptr260 := &system.JsonBoolRule{Object: ptr258, Rule: ptr259}
	ptr261 := &system.Reference{Package: "kego.io/json", Name: "@string"}
	ptr262 := &system.Object{Description: "Json selector defining what nodes this rule should be applied to.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr261}
	ptr263 := &system.Rule{Optional: true}
	ptr264 := &system.JsonStringRule{Object: ptr262, Rule: ptr263}
	ptr265 := system.String("object")
	ptr266 := &system.Type{Object: ptr248, Basic: true, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"exclude": ptr252, "interface": ptr256, "optional": ptr260, "selector": ptr264}, Is: []*system.Reference(nil), Native: &ptr265, Rule: (*system.Type)(nil)}
	ptr267 := &system.Reference{Package: "kego.io/system", Name: "string"}
	ptr268 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr269 := &system.Object{Description: "This is the native json string data type", Id: ptr267, Rules: []system.RuleInterface(nil), Type: ptr268}
	ptr270 := system.String("string")
	ptr271 := &system.Type{Object: ptr269, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface(nil), Is: []*system.Reference(nil), Native: &ptr270, Rule: ptr171}
	ptr272 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr273 := &system.Reference{Package: "kego.io/system", Name: "type"}
	ptr274 := &system.Object{Description: "This is the most basic type.", Id: ptr272, Rules: []system.RuleInterface(nil), Type: ptr273}
	ptr275 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr276 := &system.Object{Description: "Basic types don't have system:object added by default to the embedded types.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr275}
	ptr277 := &system.Rule{Optional: true}
	ptr278 := &system.JsonBoolRule{Object: ptr276, Rule: ptr277}
	ptr279 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr280 := &system.Object{Description: "Types which this should embed - system:object is always added unless basic = true.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr279}
	ptr281 := &system.Rule{Optional: true}
	ptr282 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr283 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr282}
	ptr284 := &system.Rule{}
	ptr285 := &system.ReferenceRule{Object: ptr283, Rule: ptr284, Default: (*system.Reference)(nil)}
	ptr286 := &system.ArrayRule{Object: ptr280, Rule: ptr281, Items: ptr285, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr287 := &system.Reference{Package: "kego.io/system", Name: "@map"}
	ptr288 := &system.Object{Description: "Each field is listed with it's type", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr287}
	ptr289 := &system.Rule{Optional: true}
	ptr290 := &system.Reference{Package: "kego.io/system", Name: "@rule"}
	ptr291 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr290}
	ptr292 := &system.Rule{Interface: true}
	ptr293 := &system.RuleRule{Object: ptr291, Rule: ptr292}
	ptr294 := &system.MapRule{Object: ptr288, Rule: ptr289, Items: ptr293, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr295 := &system.Reference{Package: "kego.io/json", Name: "@bool"}
	ptr296 := &system.Object{Description: "Is this type an interface?", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr295}
	ptr297 := &system.Rule{Optional: true}
	ptr298 := &system.JsonBoolRule{Object: ptr296, Rule: ptr297}
	ptr299 := &system.Reference{Package: "kego.io/system", Name: "@array"}
	ptr300 := &system.Object{Description: "Array of interface types that this type should support", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr299}
	ptr301 := &system.Rule{Optional: true}
	ptr302 := &system.Reference{Package: "kego.io/system", Name: "@reference"}
	ptr303 := &system.Object{Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr302}
	ptr304 := &system.Rule{}
	ptr305 := &system.ReferenceRule{Object: ptr303, Rule: ptr304, Default: (*system.Reference)(nil)}
	ptr306 := &system.ArrayRule{Object: ptr300, Rule: ptr301, Items: ptr305, MaxItems: (*system.Int)(nil), MinItems: (*system.Int)(nil)}
	ptr307 := &system.Reference{Package: "kego.io/system", Name: "@string"}
	ptr308 := &system.Object{Description: "This is the native json type that represents this type. If omitted, default is object.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr307}
	ptr309 := &system.Rule{Optional: true}
	ptr310 := system.String("object")
	ptr311 := &system.StringRule{Object: ptr308, Rule: ptr309, Default: &ptr310, Enum: []string{"string", "number", "bool", "array", "object", "map"}, Equal: (*system.String)(nil), Format: (*system.String)(nil), MaxLength: (*system.Int)(nil), MinLength: (*system.Int)(nil), Pattern: (*system.String)(nil)}
	ptr312 := &system.Reference{Package: "kego.io/system", Name: "@type"}
	ptr313 := &system.Object{Description: "Type that defines restriction rules for this type.", Id: (*system.Reference)(nil), Rules: []system.RuleInterface(nil), Type: ptr312}
	ptr314 := &system.Rule{Optional: true}
	ptr315 := &system.TypeRule{Object: ptr313, Rule: ptr314}
	ptr316 := system.String("object")
	ptr317 := &system.Type{Object: ptr274, Embed: []*system.Reference(nil), Fields: map[string]system.RuleInterface{"basic": ptr278, "embed": ptr286, "fields": ptr294, "interface": ptr298, "is": ptr306, "native": ptr311, "rule": ptr315}, Is: []*system.Reference(nil), Native: &ptr316, Rule: (*system.Type)(nil)}
	system.Register("kego.io/system", "@array", ptr23, 0x6eab209bb7c67261)
	system.Register("kego.io/system", "@bool", ptr33, 0x99f09d4d8377c2f6)
	system.Register("kego.io/system", "@int", ptr55, 0xcfdd76bad69c7b35)
	system.Register("kego.io/system", "@map", ptr75, 0x81bbbdddd4851344)
	system.Register("kego.io/system", "@number", ptr105, 0x392342d28da9f896)
	system.Register("kego.io/system", "@object", ptr111, 0x88b237630565f154)
	system.Register("kego.io/system", "@package", ptr117, 0x5168e36553335f0b)
	system.Register("kego.io/system", "@reference", ptr127, 0xecda4ba48ecb2d27)
	system.Register("kego.io/system", "@rule", ptr133, 0xb1194b97d6d9cd62)
	system.Register("kego.io/system", "@string", ptr171, 0xaeb6afcd8077ac5c)
	system.Register("kego.io/system", "@type", ptr177, 0x9647539a0b5c4b68)
	system.Register("kego.io/system", "array", ptr182, 0x6eab209bb7c67261)
	system.Register("kego.io/system", "bool", ptr187, 0x99f09d4d8377c2f6)
	system.Register("kego.io/system", "int", ptr192, 0xcfdd76bad69c7b35)
	system.Register("kego.io/system", "map", ptr197, 0x81bbbdddd4851344)
	system.Register("kego.io/system", "number", ptr202, 0x392342d28da9f896)
	system.Register("kego.io/system", "object", ptr227, 0x88b237630565f154)
	system.Register("kego.io/system", "package", ptr240, 0x5168e36553335f0b)
	system.Register("kego.io/system", "reference", ptr245, 0xecda4ba48ecb2d27)
	system.Register("kego.io/system", "rule", ptr266, 0xb1194b97d6d9cd62)
	system.Register("kego.io/system", "string", ptr271, 0xaeb6afcd8077ac5c)
	system.Register("kego.io/system", "type", ptr317, 0x9647539a0b5c4b68)
}
